### ISSUE TITLE
I see Duty Free when I go to URL

### ISSUE THREAD

**Issue by Pivotal-Kevin-Curley** [concourse/dutyfree#1]
As an OSS Concourse user when I go to URL dutyfree.cfapps.io

I see a page with the text Duty Free as the header.

# Acceptance Criteria
Given I am an OSS Concourse User
When I go to dutyfree.cfapps.io
I see a page with the text Duty Free as the header.

# PM Notes

- Flexible on URL. Have assumed application on PWS but a new story can be added to update a URL of the teams choice.
- Do not expect heavy styling this will be handled later with future design stories.
- This story is intentional simple to allow for the technical requirements to be included

**Comment by carlo-colombo** [comment]
If we are ending up using github pages the url (at the start at least will be https://concourse.github.io/dutyfree/)

**Comment by carlo-colombo** [comment]
Page available at https://concourse.github.io/dutyfree/

**Comment by Pivotal-Kevin-Curley** [comment]
Accepted by [Pivotal-Kevin-Curley](https://github.com/Pivotal-Kevin-Curley). Behaviour is as per acceptance criteria.
