### ISSUE TITLE
Initialize dutyfree as an elm project.

### ISSUE THREAD

**Issue by YoussB** [concourse/dutyfree#109]
## Background:
- Now that we are moving into a supported marketplace for Concourse, We thought it should be great if we have an similar structure to the Concourse codebase.
- That being, an ELM based frontend with a golang backend API.

## Acceptance Criteria:
- [ ] have the ELM project up and running with the banner.
![Frame 4 8](https://user-images.githubusercontent.com/17758967/68132519-dd4c1a80-feec-11e9-80b3-27b836a42991.png)

## Design:
- the banner background: 
![background](https://user-images.githubusercontent.com/17758967/68132743-3320c280-feed-11e9-8d5c-a4233cc4ad20.png)
- [Link to frame](https://www.figma.com/file/pmLRwbPKrwDAGn6XLDoUiA/Concourse-Resources?node-id=508%3A0)

**Comment by ibagha** [comment]
Link to banner image at 3x
![Frame 4 8](https://user-images.githubusercontent.com/54036938/68142988-534c8380-fee5-11e9-9410-21569086f964.png)

**Comment by jomsie** [comment]
I'm gonna add on this story a bit with my idea of what should happen here!

1. Setup a new elm project (elm init), also set up test framework (elm-test)
2. Create a new module or two, can talk about structure of this app
3. TDD that banner!

ps: we should expand our scope and randomly generate a new concoursey banner image each time we refresh 😅

**Comment by jomsie** [comment]
@YoussB @ibagha so we have https://github.com/concourse/dutyfree/issues/82 as well, should this issue be scaled back to just set up an elm project and thats all?

**Comment by jomsie** [comment]
just going to give some context on a css rule i applied:
`grid-template-columns : [minmax](https://developer.mozilla.org/en-US/docs/Web/CSS/minmax)(auto, 400px)`

i noticed on firefox when the screen is super small (smaller than chrome allows by default) it'd be smaller than 400px width, so the banner body text would not show properly...

![Screen Shot 2019-11-07 at 11 32 49 AM](https://user-images.githubusercontent.com/2362482/68407970-74fe7280-0152-11ea-8a9d-0a3608cfd8cd.png)

so adding that rule displays it like this:

![Screen Shot 2019-11-07 at 11 24 25 AM](https://user-images.githubusercontent.com/2362482/68408002-88a9d900-0152-11ea-8aad-100711f49b86.png)

and when the width of the window is wider than 400px it looks normal:
![Screen Shot 2019-11-07 at 11 24 30 AM](https://user-images.githubusercontent.com/2362482/68408056-a0815d00-0152-11ea-9284-eca0a02b0cc0.png)

**Comment by jomsie** [comment]
> Link to banner image at 3x
> ![Frame 4 8](https://user-images.githubusercontent.com/54036938/68142988-534c8380-fee5-11e9-9410-21569086f964.png)

just wondering if we could get a seamless version of it? (i have no idea how hard it would be to create 😅 )

cause it looks like this when its wide wide:
![Screen Shot 2019-11-07 at 11 36 22 AM](https://user-images.githubusercontent.com/2362482/68408211-f3f3ab00-0152-11ea-8c94-c0e9d4787650.png)

but that's with an infinite width on the banner, we could stick to a max width of 1024px like the width of the wireframe...

**Comment by YoussB** [comment]
Another version of that could be with the image itself stretching, as follows:
- small screen:
![Screen Shot 2019-11-07 at 11 59 21 AM](https://user-images.githubusercontent.com/17758967/68410087-25ba4100-0156-11ea-9f2b-9b92b8aa1f01.png)
- large screen:
![Screen Shot 2019-11-07 at 11 59 11 AM](https://user-images.githubusercontent.com/17758967/68410122-38347a80-0156-11ea-851f-e93c2f5864d3.png)

**Comment by jomsie** [comment]
![ezgif com-crop](https://user-images.githubusercontent.com/2362482/68410718-328b6480-0157-11ea-9316-0a14d9e0a9d7.gif)

**Comment by YoussB** [comment]
Why have a gif when we can have the whole thing live 😁 
http://dutyfree.cfapps.io/
^^ Just experimenting with the way we are going to deploy.

**Comment by ibagha** [comment]
@jomsie What do you mean by a seamless version? The wrapping looks good, I think we should also update the font sizes to be responsive to the screen widths.

**Comment by jomsie** [comment]
@ibagha if we wanted to tile the background instead of stretch, it could be a seamless background where many copies of the background image would look normal being next to one another.

but since we're going with stretching, my comment doesn't apply :)

i'll play around with some responsive font sizing!

**Comment by ibagha** [comment]
I was actually thinking about tiling the background. Let me play around with that and see how it renders.

**Comment by jomsie** [comment]
also @ibagha @YoussB are we going to have a maximum and minimum supported resolution on our site? i don't want to over complicate things by optimizing the font size responsiveness for 150px width if its not "supported" :D

**Comment by YoussB** [comment]
Remaining work:
- @ibagha to update the story with responsive font sizes for big screens.
- engineering work to be done.

**Comment by jomsie** [comment]
so we're gonna hold off on any more banner changes due to external assistance! :D
