### ISSUE TITLE
[ci] Pipeline update

### ISSUE THREAD

**Issue by YoussB** [concourse/dutyfree#118]
### Background:
- The aim of the story is to make sure that the current [pipeline](https://ci.concourse-ci.org/teams/duty-free/pipelines/dutyfree) is testing and deploying the latest elm based frontend.
- For the time being we'll keep the current pipeline tasks deploying the older version.
- in later iteration we'll build on that pipeline to include any needed automation process.

### Acceptance Criteria:
- [x] change branch to develop
- [x] set pipeline under CI
- [x] store secrets in vault
- [x] merge `pipeline` branch to `develop`
- [x] the latest elm based code is deployed to https://concourse.github.io/dutyfree/elmsite

**Comment by YoussB** [comment]
- make sure we have a dutyfree pws account to use for the hosting.

**Comment by jomsie** [comment]
we started working on this, but the prod bosh director isn't in the best (working) state at the moment. so we kinda put this off for today, and hopefully tomorrow we can pick this back up and finish it relatively quick.
