### ISSUE TITLE
Chore: Include a static CSS file in the final output

### ISSUE THREAD

**Issue by Pivotal-Kevin-Curley** [concourse/dutyfree#13]

**Comment by carlo-colombo** [comment]
We decided to include to create a static directory and copy that to the destination folder. The static folder can contains logos and other static assets that can be needed for the website.

The copy of the static directory is implemented in the dutyfree executable to have a single component responsible to create and move files for the resulting website. We don' want to share these between the go program and the pipeline. This will also help local development as just running `go run main.go <dest-dir> resources.yml` will be enough to replicate the structure that is on the `gh-pages` branch.
