### ISSUE TITLE
List a subset of Resources

### ISSUE THREAD

**Issue by Pivotal-Kevin-Curley** [concourse/dutyfree#2]
As an OSS Concourse user when I go to the URL dutyfree.cfapp.io I see a sample list of the resources currently available on the Github Wiki. Show 2 to 3 of the existing resources.
So that I can see a subset of resources in the Duty Free Page.

Given that I have a `resources.YAML` file in the Duty Free Github Repo
When an **OSS Concourse User** loads the URL
an **OSS Concourse User** can then see the list of resources and the associated resource URL

# Notes on Resource.yml

resources.YAML we expect this to be at the root level of this Repo 
Expected format 

```
resources:
???? TBD from engineering
```

**Comment by carlo-colombo** [comment]
available at https://concourse.github.io/dutyfree/

**Comment by Pivotal-Kevin-Curley** [comment]
Accepted by [Pivotal-Kevin-Curley](https://github.com/Pivotal-Kevin-Curley) behaviour is as expected in acceptance criteria.
