### ISSUE TITLE
Catalog page layout

### ISSUE THREAD

**Issue by msummerville** [concourse/dutyfree#23]
Use this Figma prototype as a guideline for the catalog page layout. We'll pair to refine

https://www.figma.com/proto/BklJP6VcyVCewBZKT8UdVVrM/Concourse-Duty-Free-Prototype-v1?node-id=82%3A354&scaling=min-zoom

**Comment by olwynlee** [comment]
@carlo-colombo @monika-hrda 

If you click on the elements in the[ Figma prototype ](https://www.figma.com/file/BklJP6VcyVCewBZKT8UdVVrM/Concourse-Duty-Free-Prototype-v1?node-id=388%3A564 )you will see on the right of the screen there is a code tab; if you click on this it will give you the CSS styling for the elements on the page

Below is an example using the resource card
Note there may be slight differences in positioning of elements across the cards, use the first card i.e. the BitBucket Notification card as shown in the example below as the source of truth.

<img width="1085" alt="Screenshot 2019-06-25 at 13 50 01" src="https://user-images.githubusercontent.com/45432881/60099887-78b7cc80-9750-11e9-8b25-9579581eb191.png">
