### ISSUE TITLE
I can see the Resource details in a new page

### ISSUE THREAD

**Issue by Pivotal-Kevin-Curley** [concourse/dutyfree#3]
As an OSS Concourse user when I click on a particular resource I am brought to a new page.
On the new page I can see the name of the resource and the URL

# Acceptance
Given A list of resources 
When I click on an individual resource I am brought to a new page with the name and the URL of the resource

PM Notes: How we choose to structure the URL can be left for IPM.

**Comment by monika-hrda** [comment]
Each resource now has its own detail page. Their URL was generated from the unique repository URL. 

e.g.

https://github.com/concourse/time-resource > `/resources/concourse-time-resource.html`
https://github.com/google/concourse-resources/tree/master/gerrit > `/resources/google-concourse-resources-tree-master-gerrit.html`

**Comment by Pivotal-Kevin-Curley** [comment]
Accepted by [pivotal-kevin-curley](https://github.com/Pivotal-Kevin-Curley) behaviour is as per the acceptance criteria.

Acceptance steps - go to https://concourse.github.io/dutyfree/

Click on a resource and I get brought to the details page showing as per the attached image.
![Screen Shot 2019-06-07 at 09 56 53](https://user-images.githubusercontent.com/46486754/59092934-9f7da280-890a-11e9-9ea2-fa38420e057f.png)
