### ISSUE TITLE
I can see the latest version of the resource on the resource card and the details page

### ISSUE THREAD

**Issue by Pivotal-Kevin-Curley** [concourse/dutyfree#33]
**Description:**
**As a** Concourse user 
**When** I am on the catalog page
**I can** see the version of the latest release associated with each resource on the **resource card and** the **details page**
**So that** I can know if I have the latest version
**And** I can gauge the maturity of the resource

**Acceptance Criteria**
**Given** I am on the Duty Free Page 
**I see** the list of resources and the version of the latest release associated with each resource on the **resource card** **and** the **details page**.

**Comment by monika-hrda** [comment]
This is development finished, as soon as we get an update to the `resources.yml` the DutyFree website will get updated

^^ @olwynlee

**Comment by olwynlee** [comment]
@carlo-colombo @monika-hrda 

accepting

Thanks for this. Can see the version updates when the resource.yml file is updated.
