### ISSUE TITLE
Explore - What Metrics are available and are meaningful to a user to measure popularity

### ISSUE THREAD

**Issue by Pivotal-Kevin-Curley** [concourse/dutyfree#34]
**Description:** What Metrics are available and are meaningful to a user to measure popularity of a resource

All users have said that they would find know the popularity of a resource relative to the other resources would give them value and help them choose if they want to use a particular resource or to choose between two similar resources.

Users have mentioned Github stars and Docker Image pulls as two metrics they felt would have value.

**Acceptance Criteria:**
A list of which Metrics are the most meaningful.
Ideally something showing that Metric for each resource so we can get a sanity check from the Concourse team.

**Comment by carlo-colombo** [comment]
### Concourse resources

* https://github.com/concourse/git-resource
* https://github.com/concourse/semver-resource
* https://github.com/concourse/pool-resource

### Community resources
* https://github.com/telia-oss/github-pr-resource
* https://github.com/frodenas/gcs-resource
* https://github.com/carlo-colombo/telegram-resource
* https://github.com/seadowg/hockey-resource

**Comment by olwynlee** [comment]
@carlo-colombo @monika-hrda This is great! Thank you both for this. I will incorporate the above into the next prototype. 

Thanks!
Olwyn

**Comment by Pivotal-Kevin-Curley** [comment]
@carlo-colombo @monika-hrda thanks for that. That's really useful. My thinking is we add the GitHub stars. It has come up in several interviews and it sounds like it isn't too expensive to add.

I like the idea of the downloads as well but I think that requires a slightly longer conversation.

Any thoughts objections?

I will accept and close the story.
