### ISSUE TITLE
I can see if a given resource is one of the Official Concourse or a Community Contributed resource

### ISSUE THREAD

**Issue by Pivotal-Kevin-Curley** [concourse/dutyfree#35]
**Description:**
**As a** Concourse user
**When I** am on the duty free home page 
**I can** I can see which resources are official Concourse resources and which are community resources 
**So that** I can have confidence in the resource I choose

**Acceptance Criteria**
**Given** I am on the Duty Free Page
**When** I click on a category on the side of the page (e.g. Notifications)
**I see** which resources are official Concourse resources and which are community resources

PM Notes: Exact icon/badge/indicator to be confirmed with design.

**Comment by olwynlee** [comment]
@carlo-colombo @monika-hrda Thank you both! I may change position and may use an icon. But these should be small changes and certainly not a priority. Will include in iteration 4 prototype.

Thanks,
Olwyn :o)

**Comment by Pivotal-Kevin-Curley** [comment]
Accepted by @Pivotal-Kevin-Curley. Behaviour as per the acceptance criteria.

![image](https://user-images.githubusercontent.com/46486754/60099604-e6afc400-974f-11e9-9ec0-f9e795ed624b.png)
