### ISSUE TITLE
I can see if a resource supports GET or PUT or both

### ISSUE THREAD

**Issue by Pivotal-Kevin-Curley** [concourse/dutyfree#36]
**As an** OSS Concourse User when I go to https://concourse.github.io/dutyfree/ I can see if a resource supports GET or PUT or both.

**So that** I can see if the resource supports my requirements.

**Acceptance Criteria**
**When I** go to https://concourse.github.io/dutyfree/ 
**I can see** whether a resource supports GET or PUT tag or both. These tags will display on the resource tile and also the resource detail page.

PM Notes: GET / PUT tags to be added to the resources.yml file by @Pivotal-Kevin-Curley . 
Check with design for look and location of GET & PUT tags

**Comment by Pivotal-Kevin-Curley** [comment]
Accepted by @Pivotal-Kevin-Curley. Behaviour is as per the acceptance criteria.

![image](https://user-images.githubusercontent.com/46486754/60195694-74b0ab00-9833-11e9-86c1-0fb900e018dd.png)

**Comment by Pivotal-Kevin-Curley** [comment]
Didn't notice at acceptance that this hadn't been added to the details page. Will accepted story again once it has been added to the details page. 

Placement for the GET/PUT tag should be 25 pixels below the description aligned to the left with the description title and description text.

**Comment by carlo-colombo** [comment]
Pushed change to branch https://github.com/concourse/dutyfree/tree/freeze-1 while waiting for today's interviews. Will move to _Ready to accept_ once merged

**Comment by carlo-colombo** [comment]
merged into master and published

**Comment by msummerville** [comment]
The font size on the get/put tags doesn't match the prototype (it's larger) but I'm accepting the story because the way it's implemented is an improvement over the design.
