### ISSUE TITLE
I can see the information on the details page laid out in a way that reflects the prototype

### ISSUE THREAD

**Issue by Pivotal-Kevin-Curley** [concourse/dutyfree#39]
Description: As a User 
I can see the information on the details page laid out in a way that reflects the figma prototype [**_iteration 4 - Detail page**](https://www.figma.com/file/BklJP6VcyVCewBZKT8UdVVrM/Concourse-Duty-Free-Prototype-v1?node-id=409%3A217) 
So that I can easily read the information

Please update the following to reflect the prototype details page:

1. Example
2. Last commit date
3. Version beside title
4. Put/Get label
5. Author name and GitHub avatar
6. Thin grey line between 'Example' and 'Description'
7. GitHub icon beside resource title

Acceptance Criteria: When I go to the Duty Free Page I see the information on the details page laid out in a way that reflects the prototype as agreed with design.

**Comment by Pivotal-Kevin-Curley** [comment]
@olwynlee list and sort the changes that need to be done

**Comment by carlo-colombo** [comment]
- [ ] Example
- [ ] Last commit date
- [ ] Version beside title
- [ ] Put/Get label
- [ ] Author name and GitHub avatar
- [ ] Thin grey line between 'Example' and 'Description'
- [ ] GitHub icon beside resource title

**Comment by msummerville** [comment]
I'm leaving this open pending feedback on "thin grey line." I have add a placeholder to the icebox for a story re: the author avatar

**Comment by carlo-colombo** [comment]
closing this as cosmetic overhaul will be done by concourse team
