### ISSUE TITLE
Render the Readme from Github

### ISSUE THREAD

**Issue by Pivotal-Kevin-Curley** [concourse/dutyfree#4]
As an **OSS Concourse User** when I click on a particular resource I am brought to the details page. 
I see the Readme file from Github displayed on the page. The Readme file should be no older than 24 hours.

So that I can understand more detail about the resource including what the Resource does and how I should use it.

# Acceptance

**Scenario 1**
Given I am on the Duty Free home page 
When I click on a particular resource
I see the details page for that resource which displays the Readme file for the same resource that I clicked on.

**Scenario 2**
Given I am on the Duty Free home page 
When I click on a particular resource that has been updated more than 24 hours ago
I see the details page for that resource which displays the correct Readme file for the same resource that I clicked on.

### Dev Notes
- retrieve rendered html: `curl -H 'Accept: application/vnd.github.VERSION.html' https://api.github.com/repos/carlo-colombo/telegram-resource/readme`
- unrendered markdown: `curl -H 'Accept: application/vnd.github.VERSION.raw' https://api.github.com/repos/carlo-colombo/telegram-resource/readme `

### Dev tasks

- [ ] generate a token for duty free team/repository moving away from personal
- [x] refactor tests to use mock github server instead of real gh
- [x] add token to lastpass account
- [x] use token in pipeline to generate html

**Comment by carlo-colombo** [comment]
@concourse/duty-free what we should do if retrieving the readme generate an error (eg github is down)

**Comment by carlo-colombo** [comment]
At the moment we are using a personal token instead of one from a machine user (@concourse-bot), add to the pipeline to run every day (morning utc time) to rebuild the website to keep the readme fresh

**Comment by Pivotal-Kevin-Curley** [comment]
Accepted by @Pivotal-Kevin-Curley. Behaviour is as per acceptance criteria.
