### ISSUE TITLE
I can see the number of Github stars associated with each resource

### ISSUE THREAD

**Issue by Pivotal-Kevin-Curley** [concourse/dutyfree#40]
As an OSS Concourse User when I go to https://concourse.github.io/dutyfree/ I can see the number of Github stars associated with each resource on the resource card and the details page

So that I can gauge the popularity of the resource which will help me choose the right resource for my requirements

**Acceptance Criteria**
When I go to https://concourse.github.io/dutyfree/ 
**I see** The Github stars on the resource card
**And** I see the Github stars when I click through to the details page.

PM Notes: See Figma prototype for where Github stars should be located on resource card and details page.

**Comment by monika-hrda** [comment]
This story has been implemented, but loading the github star information from an external website (as an image) has the side-effect of a longer loading time.  Experience between users may vary, e.g. depending on connectivity.

**Comment by Pivotal-Kevin-Curley** [comment]
Accepted by @Pivotal-Kevin-Curley. Behaviour is as per acceptance criteria and the content matches what is on Github.

![image](https://user-images.githubusercontent.com/46486754/60263668-2ce45f00-98d9-11e9-81f7-08f558a96862.png)

**Comment by Pivotal-Kevin-Curley** [comment]
Accepted for first part of the story. I missed that the stars had not been added to the Details page. Can we add to the details page and I will accept the story again. Thanks

**Comment by msummerville** [comment]
format and placement against the details page verified against https://www.figma.com/file/BklJP6VcyVCewBZKT8UdVVrM/Concourse-Duty-Free-Prototype-v1?node-id=409%3A217

as a side note, I would have broken this into multiple stories; one for card and one for details page.
