### ISSUE TITLE
I can see the last commit for each resource

### ISSUE THREAD

**Issue by Pivotal-Kevin-Curley** [concourse/dutyfree#41]
As an OSS Concourse User when I go to https://concourse.github.io/dutyfree/ 

I can see an indication of time since the last commit for each resource on the details page.

So that I can see how active a resource is

**Acceptance Criteria**
When I go to https://concourse.github.io/dutyfree/ 
**I see** an indication of time since the last commit for each resource on the details page.

PM Notes: See the [Figma iteration 4 prototype](https://www.figma.com/file/BklJP6VcyVCewBZKT8UdVVrM/Concourse-Duty-Free-Prototype-v1?node-id=388%3A564) for suggested placing.

**Comment by olwynlee** [comment]
@carlo-colombo @monika-hrda 

accepting.

thank you both!
