### ISSUE TITLE
I should see a Concourse logo on the card for the resources authored by the Concourse team

### ISSUE THREAD

**Issue by Pivotal-Kevin-Curley** [concourse/dutyfree#42]
As an OSS Concourse User when I go to https://concourse.github.io/dutyfree/ I can 

So that I can can see what categories are available

**Acceptance Criteria**
When I go to https://concourse.github.io/dutyfree/ 
**I see** 

PM Notes: Concourse image saved [here](https://drive.google.com/drive/u/1/folders/19LcTKOqh0DCKFy-chWjU_yzyPMAYfAVX) in Duty Free drive

**Comment by ibagha** [comment]
Verified resources are out of scope for v1. The extra scope for this will include defining criteria for what is a 'verified' resource, both internally with the Concourse team as well as with resource authors.
