### ISSUE TITLE
I should see on the resource cards a label that shows if a resource has been verified by the Concourse team

### ISSUE THREAD

**Issue by Pivotal-Kevin-Curley** [concourse/dutyfree#43]
As an OSS Concourse User when I go to https://concourse.github.io/dutyfree/ 

I can see that Concourse resources have been marked as verified.

So that I can have confidence that the resource does what I expect it do

**Acceptance Criteria**
When I go to https://concourse.github.io/dutyfree/ 
**I see** a way to see which resources the concourse team have verified.

PM Notes: Definition of what verified means and what the list of verified resources would be to confirmed with the Concourse team.

See [Figma iteration 4 prototype](https://www.figma.com/file/BklJP6VcyVCewBZKT8UdVVrM/Concourse-Duty-Free-Prototype-v1?node-id=388%3A564) for placement and styling

**Comment by Pivotal-Kevin-Curley** [comment]
Based on feedback from Concourse team can we move the verified label across to the top right hand side of the resource card.

**Comment by olwynlee** [comment]
@carlo-colombo @monika-hrda 
Accepting.

Thanks!
