### ISSUE TITLE
I should see the author avatar beside the link to the author on the details page

### ISSUE THREAD

**Issue by Pivotal-Kevin-Curley** [concourse/dutyfree#44]
As an OSS Concourse User when I go to https://concourse.github.io/dutyfree/ I can 

So that I can can see what categories are available

**Acceptance Criteria**
When I go to https://concourse.github.io/dutyfree/ 
**I see** 

PM Notes:

**Comment by YoussB** [comment]
we're going to create 2 stories for the metadata. based on: https://www.figma.com/file/pmLRwbPKrwDAGn6XLDoUiA/Concourse-Resources?node-id=553%3A0
