### ISSUE TITLE
I should see the number of resources associated with each category in the category navigation frame on the left of the homepage

### ISSUE THREAD

**Issue by Pivotal-Kevin-Curley** [concourse/dutyfree#45]
As an OSS Concourse User when I go to https://concourse.github.io/dutyfree/ 

I can see the number of resources associated with each category in the navigation frame on the left side of the home page. 

So that I can see the number of resources associated with each category

**Acceptance Criteria**
When I go to https://concourse.github.io/dutyfree/ 
**I see** the number of resources associated with each category in the navigation frame on the left side of the home page. 

PM Notes: Agreed that we don't expect this number to change when the user performs a search

**Comment by carlo-colombo** [comment]
@olwynlee at the moment longer category names make the number go to a new line. As this was not addressed in the prototype would you mind to create a story to fix it. We can discuss which priority the story could have

**Comment by olwynlee** [comment]
@carlo-colombo Thanks Carlo. The padding to the right is curretly 24px - can we reduce this and see what it looks like when the Rel Eng category is on one line.

**Comment by carlo-colombo** [comment]
@olwynlee reducing the padding does the work, but when the number of categories reach double digit it goes to a new line again. 

The longest category (as we know) and double digit need to be taken in cosideration.

Will put this story back in _to accept_, will wait for an update figma prototype and a new story.

**Comment by msummerville** [comment]
Closing this story; a placeholder is in the icebox for the double digit count / line wrapping issue
