### ISSUE TITLE
I should not see the authors name or the official tag on the resource card

### ISSUE THREAD

**Issue by Pivotal-Kevin-Curley** [concourse/dutyfree#47]
**As an** OSS Concourse User when I go to https://concourse.github.io/dutyfree/

**I do not see** the author name or official tag on any of the resources

**So that** I can easily identify which of the resources are authored and supported by the Concourse team

**Acceptance Criteria**
When I go to https://concourse.github.io/dutyfree/

**I do not see** the author name or official tag on any of the resources

**Comment by olwynlee** [comment]
@carlo-colombo @monika-hrda 
accepting

Thanks!
