### ISSUE TITLE
I should be able to see the list of categories in the navigation panel sorted by the number of resources associated with the category

### ISSUE THREAD

**Issue by Pivotal-Kevin-Curley** [concourse/dutyfree#48]
**As an** OSS Concourse User when I go to https://concourse.github.io/dutyfree/ 

**I can** see the list of categories in the navigation panel sorted by the number of resources associated with the category

**So that** I can gauge which are the most important categories

**Acceptance Criteria**
When I go to https://concourse.github.io/dutyfree/ 

**I see** the list of categories in the navigation panel sorted by the number of resources associated with the category

**Comment by ibagha** [comment]
We will not be implementing categories in v1 since we are lacking a strong use case, and the maintenance of the categories is out of scope for v1. We might reintroduce this in v2 if there is a strong signal, but the design will not live in the sidebar.
