### ISSUE TITLE
List All Resources

### ISSUE THREAD

**Issue by Pivotal-Kevin-Curley** [concourse/dutyfree#5]
As an OSS Concourse user when I go to dutyfree.cf.app.io I see the full list of resources currently available on the Resources Github Wiki.

So that I can find the resource that I want.

Given that I have a resources.YAML file in the Duty Free Github Repo
When an OSS Concourse User loads the URL
an OSS Concourse User can then see the list of resources and the associated resource URL

Notes on Resource.yml
resources.YAML we expect this to be at the root level of this Repo
Expected format

resources:
???? TBD from engineering

**Comment by carlo-colombo** [comment]
To generate `resources.yml` starting from the wiki page

1. Extract only the resources without the header and save it to a file (eg `/tmp/resources.wiki`)
2. `cat /tmp/resources.wiki | cut -d'|' -f2  | sed 's/.*\[\(.*\)\](\(.*\))/\1,\2/' > /tmp/resources-names-and-repos`

**Comment by carlo-colombo** [comment]
available at https://concourse.github.io/dutyfree/

**Comment by Pivotal-Kevin-Curley** [comment]
Accepted by [Pivotal-Kevin-Curley](https://github.com/Pivotal-Kevin-Curley). Behaviour is as expected in acceptance criteria.

**Comment by monika-hrda** [comment]
The process of generating `resources.yml`should be repeated at least once again at the end of development cycle, before the current Github page with resources gets deleted!
