### ISSUE TITLE
I should be able to example code when I am on the resource details page

### ISSUE THREAD

**Issue by Pivotal-Kevin-Curley** [concourse/dutyfree#51]
**As an** OSS Concourse User when I go to the resource details page 

**I can** see example code on 5 of the resources (engineers discretion to pick 5 examples from high quality readmes)

**So that** I can better understand how the resource works and if it meets my requirements

**Acceptance Criteria**
When I go to the resource details page of one of the 5 chosen resources
**I see** example code for the resource

**Comment by carlo-colombo** [comment]
We added single snippet usage/example from the readme to `resources.yml` for this resources

* time
* pool
* bosh errands
* cloudformation

We had some issue finding this kind of snippet, with both resource definition and use in the job, so we limited to 4.

A lot of resources don't define a snippet that we can just copy to put in the example field, for example the git-resource has 3 different snippet for resource definition, get, and put.

**Comment by olwynlee** [comment]
@carlo-colombo @monika-hrda 

Accepting

Thanks,
Olwyn
