### ISSUE TITLE
Document guidelines for Resource authors to follow when adding a resource based on research findings

### ISSUE THREAD

**Issue by carlo-colombo** [concourse/dutyfree#52]
As a resource author I want to be able to add to duty free the resource I just created

**As** resource author
**When** I look how to add a resource to duty free
**I can** find a document in the wiki that outline how

### Notes
* We expect the author to be able with a PR to add a resource to dutyfree
* The wiki page will be eventuall included in concourse documentation and or dutyfree as static page
* github provides way to template pr messages https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository - https://help.github.com/en/articles/about-issue-and-pull-request-templates

**Comment by carlo-colombo** [comment]
https://github.com/concourse/dutyfree/wiki/How-to-add-resources-to-Duty-Free

**Comment by msummerville** [comment]
leaving this open for @Pivotal-Kevin-Curley to confirm the content matches what he was expecting

**Comment by Pivotal-Kevin-Curley** [comment]
Accepted by @Pivotal-Kevin-Curley.
