### ISSUE TITLE
Create documentation for what content is editorial and how to update it

### ISSUE THREAD

**Issue by carlo-colombo** [concourse/dutyfree#53]
To help concourse team completing the `resources.yml` for all the resources

**As** A concourse team member
**When** I want to complete the resources.yml\
**I can** find a wiki page in github that outlines which fields need to be added and out to fill them

**Comment by carlo-colombo** [comment]
https://github.com/concourse/dutyfree/wiki/Content-of-a-resource-in-resources.yml

**Comment by msummerville** [comment]
leaving this open for @Pivotal-Kevin-Curley to confirm the content matches what he was expecting

**Comment by Pivotal-Kevin-Curley** [comment]
Accepted by @Pivotal-Kevin-Curley. Documentation gives explanation of how editorial content can be added.
