### ISSUE TITLE
Make sure resource YAML is up to date - recurring

### ISSUE THREAD

**Issue by carlo-colombo** [concourse/dutyfree#54]
New resource could have been added to the wiki page since we created our `resources.yml`

Check if any resource has been added since **06/06/2019** , if yes add to the bottom of `resources.yml` with all the field compiled (get,put, verified, description)

Procedure to import multiple resource done in #5

**Comment by monika-hrda** [comment]
A new resource was added to `resources.yml` on Tue 9 July at 10am.
