### ISSUE TITLE
category is still selected after searching

### ISSUE THREAD

**Issue by jtarchie** [concourse/dutyfree#61]
When I selected "Integration" as a category,
And then searched "git",
The "Integration" was still selected.

<img width="1122" alt="Screen Shot 2019-07-09 at 5 16 22 PM" src="https://user-images.githubusercontent.com/75184/60929176-80f22a80-a26d-11e9-9e08-b2f25eafa336.png">

Expected:

1. The search query to affect the currently selected category.
2. Or, the category to be cleared as it is no longer being used.

**Comment by ibagha** [comment]
@jtarchie Will close this issue since we won't be implementing categories for v1. Thanks for the suggestion!
