### ISSUE TITLE
The default sort for resources should be alphabetical on title

### ISSUE THREAD

**Issue by olwynlee** [concourse/dutyfree#66]
## Problem:
Currently, resources on the Duty Free home page are not sorted in any particular order. During user research users expressed a preference for having resources sorted alphabetically on title by default on both the home page and in search results. 

## Goal:
- Resources are by default displayed alphabetically on both the home page and in search results so as a user can quickly scan for a resource based on title and find the resource they are looking for.

## Validation:
Below are some examples of quotes validating the preference for resources to be displayed alphabetically by default (note some of the quotes don't explicitly state 'default' but they were asked this when questioned). 

"Would be nice to have options how it was sorted but would  expect the default to be alphabetical"
"I would expect them to be sorted alphabetically"
"expect sort alphabetical"

## Thoughts and Questions:
During user research users (particularly external customers/non-Pivots) expressed a strong preference for having verified resources displayed first on both the home page and in returned search results. [Issue #67](https://github.com/concourse/dutyfree/issues/67) has already been opened to address this and it is assumed that this has been taken into consideration before implementing the default alphabetical sort described in this issue.

## Screenshots/Link to prototype:
https://www.figma.com/file/BklJP6VcyVCewBZKT8UdVVrM/Concourse-Duty-Free-Prototype-v1?node-id=668%3A0

**Comment by olwynlee** [comment]
## Problem:
Currently, resources on the Duty Free home page are not sorted in any particular order. During user research users expressed a preference for having resources sorted alphabetically by default on both the home page and in search results. 

## Goal:
- Resources are by default displayed alphabetically on both the home page and in search results so as a user can quickly scan for a resource based on tile and find the resource they are looking for.

## Validation:
Below are some examples of quotes validating the preference for resources to be displayed alphabetically by default (note some of the quotes don't explicitly state 'default' but they were asked this when questioned). 

"Would be nice to have options how it was sorted but would  expect the default to be alphabetical"
"I would expect them to be sorted alphabetically"
"expect sort alphabetical"

## Thoughts and Questions:
During user research users (particularly external customers/non-Pivots) expressed a strong preference for having verified resources displayed first on both the home page and in returned search results. [Issue #67](https://github.com/concourse/dutyfree/issues/67) has already been opened to address this and it is assumed that this has been taken into consideration before implementing the default alphabetical sort described in this issue.

## Screenshots/Link to prototype:
> Figma or screenshots implementation details like css etc. 


> Add a Label
> Put a label on it... " web-ui", "design-snack", "needs-triage" etc...

**Comment by ibagha** [comment]
A few points on sorting by most popular vs alphabetical:
-'Most popular' (in this case, resources in order of most github stars) was found to be one of the primary pieces of information when making a decision to implement a resource. It could be more helpful to display by most popular on the homepage and in the search results.
-When we implement the 'verified' tag, resources will we sorted by verified and most popular since verified is the #1 criteria in deciding to implement one resource over another
-Cards with more stars most likely have richer content, which we'd want to display to the user over empty cards that are listed alphabetically
-There will also be a sort filter for users to sort by most popular and alphabetical if the latter is needed
