### ISSUE TITLE
I can see the catalog page

### ISSUE THREAD

**Issue by msummerville** [concourse/dutyfree#8]
**As an OSS Concourse user** when I go to https://concourse.github.io/dutyfree/ I see a structured shell of the catalog page.

**So that** I can see the way the duty free site is structured.

**Acceptance criteria:**
When I go to https://concourse.github.io/dutyfree/ I see the catalog page which contains blocks for a a header bar, left navigation bar, resource list. The page frame matches the layout of the wireframe 
https://www.figma.com/file/BklJP6VcyVCewBZKT8UdVVrM/Concourse-Duty-Free-Prototype-v1?node-id=0%3A1

PM Notes: Need to confirm the grid to be used with Concourse team. Potentially use the same grid as the Concourse docs page?

### Dev tasks

- [x] regeneration of website on code change
- [x] build a grid of some kind
- [ ] get the dimensions from design

**Comment by Pivotal-Kevin-Curley** [comment]
Blocked until we can define the grid and behaviour at multiple screen widths.

**Comment by carlo-colombo** [comment]
`brew install entr`
`ag -l | entr -r go run main.go /tmp/ resources.yml `

**Comment by Pivotal-Kevin-Curley** [comment]
Accepted by @Pivotal-Kevin-Curley. Behavior is as per acceptance criteria.
